# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --prefix frontend
      
      - name: Lint
        run: npm run lint --prefix frontend
      
      - name: Unit tests
        run: npm run test:unit --prefix frontend
      
      - name: Build
        run: npm run build --prefix frontend

  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --prefix backend
      
      - name: Security audit
        run: npm audit --prefix backend
      
      - name: Run tests
        run: npm test --prefix backend
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

  deploy:
    needs: [frontend, backend]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to production
        uses: some-deployment-action
        env:
          PRODUCTION_KEY: ${{ secrets.PRODUCTION_KEY }}
