name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR body for required sections
        if: github.event.pull_request.body == null || !contains(github.event.pull_request.body, '## Description')
        run: |
          echo "The pull request description is missing the '## Description' section."
          exit 1
