name: PR Title Check

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          if [[ ! $TITLE =~ ^(feat|fix|docs|chore|refactor):\ .+ ]]; then
            echo "❌ PR title must follow convention: 'feat|fix|docs|chore|refactor: description'"
            exit 1
          fi
